# .github/workflows/evaluation.yml
name: Use Remote Evaluation

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'src/*.py'
      - 'evaluation/evaluation.py'
      - 'src/evaluatio/evaluation.py'

jobs:
  run-evaluation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy

      - name: Run evaluation.py
        run: python evaluation/evaluation.py
        
      - name: Read results.md
        id: read_results
        run: |
          echo "RESULTS<<EOF" >> $GITHUB_ENV
          cat results.md >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Post comment to PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          COMMENTS_URL="https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
          curl -s -X POST -H "Authorization: token $GITHUB_TOKEN" \
               -H "Content-Type: application/json" \
               -d "{\"body\": \"${{ env.RESULTS }}\"}" \
               "$COMMENTS_URL"
