# .github/workflows/evaluation_parametrized_call.yml
name: 🔁 Call Evaluation Workflow (remote)

on:
  workflow_dispatch:  # Allows manual trigger from GitHub UI or CLI
  push: # Trigger on pushes to feature branches
    branches:
      - 'feature/evaluation-pipeline*' 
  pull_request: # Trigger on PRs to main branch
    types: [opened, synchronize, reopened]
    paths:
      - 'src/*.py'
      - 'evaluation/evaluation.py'
      - 'src/evaluatio/evaluation.py'

permissions:
  pull-requests: write # For commenting on PRs
  issues: write # For commenting on issues

jobs:
  trigger-evaluation:
    uses: ./.github/workflows/evaluation_parametrized.yml
    with:
      python_version: "3.11"
      working_directory: "./"
      requirements_filepath: "./requirements.txt"
      evaluation_filepath: "./evaluation/evaluation.py"
    secrets: inherit  # Passes all secrets from the calling workflow